import { Metadata } from "next";

export const metadataHome: Metadata = {
    title: "شباب نجع الدار",
    description: "Generated by create next app",
};

export const metadataMedicines: Metadata = {
    title: "شباب نجع الدار - الادوية",
    description: "Generated by create next app",
};