import { Metadata } from "next";

export const metadataHome: Metadata = {
    title: "شباب نجع الدار",
    description: "Generated by create next app",
};

export const metadataMedicines: Metadata = {
    title: "شباب نجع الدار - الادوية",
    description: "Generated by create next app",
};

export const metadataMedicinesDetails: Metadata = {
    title: "شباب نجع الدار - تفاصيل العلاج",
    description: "Generated by create next app",
};

export const metadataBlogs: Metadata = {
    title: "شباب نجع الدار - الاخبار",
    description: "Generated by create next app",
};

export const metadataBlogsDetails: Metadata = {
    title: "شباب نجع الدار - تفاصيل الاخبار",
    description: "Generated by create next app",
};